/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

TopLevel  pTopLevel(FILE *inp);
TopLevel psTopLevel(const char *str);
Expr  pExpr(FILE *inp);
Expr psExpr(const char *str);
Binop  pBinop(FILE *inp);
Binop psBinop(const char *str);
Block  pBlock(FILE *inp);
Block psBlock(const char *str);
State  pState(FILE *inp);
State psState(const char *str);
FunDecl  pFunDecl(FILE *inp);
FunDecl psFunDecl(const char *str);
Args  pArgs(FILE *inp);
Args psArgs(const char *str);
ArgsRest  pArgsRest(FILE *inp);
ArgsRest psArgsRest(const char *str);
FArgs  pFArgs(FILE *inp);
FArgs psFArgs(const char *str);
FArgsRest  pFArgsRest(FILE *inp);
FArgsRest psFArgsRest(const char *str);

#endif
