/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef PRINTER_HEADER
#define PRINTER_HEADER

#include "Absyn.h"

/* Certain applications may improve performance by changing the buffer size */
#define BUFFER_INITIAL 2048
/* You may wish to change _L_PAREN or _R_PAREN */
#define _L_PAREN '('
#define _R_PAREN ')'

/* The following are simple heuristics for rendering terminals */
/* You may wish to change them */
void renderCC(Char c);
void renderCS(String s);
void indent(void);
void backup(void);
void onEmptyLine(void);
void removeTrailingSpaces(void);
void removeTrailingWhitespace(void);


char *printTopLevel(TopLevel p);
char *printExpr(Expr p);
char *printBinop(Binop p);
char *printBlock(Block p);
char *printState(State p);
char *printFunDecl(FunDecl p);
char *printArgs(Args p);
char *printArgsRest(ArgsRest p);
char *printFArgs(FArgs p);
char *printFArgsRest(FArgsRest p);

void ppTopLevel(TopLevel p, int i);
void ppExpr(Expr p, int i);
void ppBinop(Binop p, int i);
void ppBlock(Block p, int i);
void ppState(State p, int i);
void ppFunDecl(FunDecl p, int i);
void ppArgs(Args p, int i);
void ppArgsRest(ArgsRest p, int i);
void ppFArgs(FArgs p, int i);
void ppFArgsRest(FArgsRest p, int i);

char *showTopLevel(TopLevel p);
char *showExpr(Expr p);
char *showBinop(Binop p);
char *showBlock(Block p);
char *showState(State p);
char *showFunDecl(FunDecl p);
char *showArgs(Args p);
char *showArgsRest(ArgsRest p);
char *showFArgs(FArgs p);
char *showFArgsRest(FArgsRest p);

void shTopLevel(TopLevel p);
void shExpr(Expr p);
void shBinop(Binop p);
void shBlock(Block p);
void shState(State p);
void shFunDecl(FunDecl p);
void shArgs(Args p);
void shArgsRest(ArgsRest p);
void shFArgs(FArgs p);
void shFArgsRest(FArgsRest p);

void ppInteger(Integer n, int i);
void ppDouble(Double d, int i);
void ppChar(Char c, int i);
void ppString(String s, int i);
void ppIdent(String s, int i);
void shInteger(Integer n);
void shDouble(Double d);
void shChar(Char c);
void shString(String s);
void shIdent(String s);
void bufEscapeS(const char *s);
void bufEscapeC(const char c);
void bufAppendS(const char *s);
void bufAppendC(const char c);
void bufReset(void);
void resizeBuffer(void);

#endif

