/* File generated by the BNF Converter (bnfc 2.9.6.1). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printTopLevel(TopLevel p)
{
  _n_ = 0;
  bufReset();
  ppTopLevel(p, 0);
  return buf_;
}
char *printExpr(Expr p)
{
  _n_ = 0;
  bufReset();
  ppExpr(p, 0);
  return buf_;
}
char *printBinop(Binop p)
{
  _n_ = 0;
  bufReset();
  ppBinop(p, 0);
  return buf_;
}
char *printBlock(Block p)
{
  _n_ = 0;
  bufReset();
  ppBlock(p, 0);
  return buf_;
}
char *printState(State p)
{
  _n_ = 0;
  bufReset();
  ppState(p, 0);
  return buf_;
}
char *printFunDecl(FunDecl p)
{
  _n_ = 0;
  bufReset();
  ppFunDecl(p, 0);
  return buf_;
}
char *printArgs(Args p)
{
  _n_ = 0;
  bufReset();
  ppArgs(p, 0);
  return buf_;
}
char *printArgsRest(ArgsRest p)
{
  _n_ = 0;
  bufReset();
  ppArgsRest(p, 0);
  return buf_;
}
char *printFArgs(FArgs p)
{
  _n_ = 0;
  bufReset();
  ppFArgs(p, 0);
  return buf_;
}
char *printFArgsRest(FArgsRest p)
{
  _n_ = 0;
  bufReset();
  ppFArgsRest(p, 0);
  return buf_;
}
char *showTopLevel(TopLevel p)
{
  _n_ = 0;
  bufReset();
  shTopLevel(p);
  return buf_;
}
char *showExpr(Expr p)
{
  _n_ = 0;
  bufReset();
  shExpr(p);
  return buf_;
}
char *showBinop(Binop p)
{
  _n_ = 0;
  bufReset();
  shBinop(p);
  return buf_;
}
char *showBlock(Block p)
{
  _n_ = 0;
  bufReset();
  shBlock(p);
  return buf_;
}
char *showState(State p)
{
  _n_ = 0;
  bufReset();
  shState(p);
  return buf_;
}
char *showFunDecl(FunDecl p)
{
  _n_ = 0;
  bufReset();
  shFunDecl(p);
  return buf_;
}
char *showArgs(Args p)
{
  _n_ = 0;
  bufReset();
  shArgs(p);
  return buf_;
}
char *showArgsRest(ArgsRest p)
{
  _n_ = 0;
  bufReset();
  shArgsRest(p);
  return buf_;
}
char *showFArgs(FArgs p)
{
  _n_ = 0;
  bufReset();
  shFArgs(p);
  return buf_;
}
char *showFArgsRest(FArgsRest p)
{
  _n_ = 0;
  bufReset();
  shFArgsRest(p);
  return buf_;
}
void ppTopLevel(TopLevel p, int _i_)
{
  switch(p->kind)
  {
  case is_TLCons:
    if (_i_ > 0) renderC(_L_PAREN);
    ppFunDecl(p->u.tLCons_.fundecl_, 0);
    ppTopLevel(p->u.tLCons_.toplevel_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TLNil:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing TopLevel!\n");
    exit(1);
  }
}

void ppExpr(Expr p, int _i_)
{
  switch(p->kind)
  {
  case is_EVar:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.eVar_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ETrue:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("true");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EFalse:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("false");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EInt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.eInt_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EBinOp:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.eBinOp_.expr_1, 0);
    ppBinop(p->u.eBinOp_.binop_, 0);
    ppExpr(p->u.eBinOp_.expr_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EFnCall:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.eFnCall_.ident_, 0);
    renderC('(');
    ppFArgs(p->u.eFnCall_.fargs_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expr!\n");
    exit(1);
  }
}

void ppBinop(Binop p, int _i_)
{
  switch(p->kind)
  {
  case is_Add:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('+');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Sub:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('-');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Mul:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('*');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Div:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('/');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Lte:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("<=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Eq:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("==");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Neq:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("!=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Gte:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS(">=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Lt:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Gt:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_And:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("&&");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Or:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("||");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Binop!\n");
    exit(1);
  }
}

void ppBlock(Block p, int _i_)
{
  switch(p->kind)
  {
  case is_BCons:
    if (_i_ > 0) renderC(_L_PAREN);
    ppState(p->u.bCons_.state_, 0);
    ppBlock(p->u.bCons_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_BNil:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Block!\n");
    exit(1);
  }
}

void ppState(State p, int _i_)
{
  switch(p->kind)
  {
  case is_SAssn:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.sAssn_.ident_, 0);
    renderC('=');
    ppExpr(p->u.sAssn_.expr_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SPrint:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("print");
    ppExpr(p->u.sPrint_.expr_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SIf:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("if");
    ppExpr(p->u.sIf_.expr_, 0);
    renderS("then");
    ppBlock(p->u.sIf_.block_, 0);
    renderS("fi");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SIfEl:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("if");
    ppExpr(p->u.sIfEl_.expr_, 0);
    renderS("then");
    ppBlock(p->u.sIfEl_.block_1, 0);
    renderS("else");
    ppBlock(p->u.sIfEl_.block_2, 0);
    renderS("fi");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SWhile:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("while");
    ppExpr(p->u.sWhile_.expr_, 0);
    renderS("do");
    ppBlock(p->u.sWhile_.block_, 0);
    renderS("end");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SExpr:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.sExpr_.expr_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SRet:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("return");
    ppExpr(p->u.sRet_.expr_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing State!\n");
    exit(1);
  }
}

void ppFunDecl(FunDecl p, int _i_)
{
  switch(p->kind)
  {
  case is_FDecl:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("fn");
    ppIdent(p->u.fDecl_.ident_, 0);
    renderC('(');
    ppArgs(p->u.fDecl_.args_, 0);
    renderC(')');
    ppBlock(p->u.fDecl_.block_, 0);
    renderS("end");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FunDecl!\n");
    exit(1);
  }
}

void ppArgs(Args p, int _i_)
{
  switch(p->kind)
  {
  case is_AArgs:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.aArgs_.ident_, 0);
    ppArgsRest(p->u.aArgs_.argsrest_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ANone:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Args!\n");
    exit(1);
  }
}

void ppArgsRest(ArgsRest p, int _i_)
{
  switch(p->kind)
  {
  case is_ACons:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC(',');
    ppIdent(p->u.aCons_.ident_, 0);
    ppArgsRest(p->u.aCons_.argsrest_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ANil:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ArgsRest!\n");
    exit(1);
  }
}

void ppFArgs(FArgs p, int _i_)
{
  switch(p->kind)
  {
  case is_FAArgs:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.fAArgs_.expr_, 0);
    ppFArgsRest(p->u.fAArgs_.fargsrest_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_FANone:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FArgs!\n");
    exit(1);
  }
}

void ppFArgsRest(FArgsRest p, int _i_)
{
  switch(p->kind)
  {
  case is_FACons:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC(',');
    ppExpr(p->u.fACons_.expr_, 0);
    ppFArgsRest(p->u.fACons_.fargsrest_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_FANil:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FArgsRest!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void shTopLevel(TopLevel p)
{
  switch(p->kind)
  {
  case is_TLCons:
    bufAppendC('(');

    bufAppendS("TLCons");

    bufAppendC(' ');

    shFunDecl(p->u.tLCons_.fundecl_);
  bufAppendC(' ');
    shTopLevel(p->u.tLCons_.toplevel_);

    bufAppendC(')');

    break;
  case is_TLNil:

    bufAppendS("TLNil");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing TopLevel!\n");
    exit(1);
  }
}

void shExpr(Expr p)
{
  switch(p->kind)
  {
  case is_EVar:
    bufAppendC('(');

    bufAppendS("EVar");

    bufAppendC(' ');

    shIdent(p->u.eVar_.ident_);

    bufAppendC(')');

    break;
  case is_ETrue:

    bufAppendS("ETrue");




    break;
  case is_EFalse:

    bufAppendS("EFalse");




    break;
  case is_EInt:
    bufAppendC('(');

    bufAppendS("EInt");

    bufAppendC(' ');

    shInteger(p->u.eInt_.integer_);

    bufAppendC(')');

    break;
  case is_EBinOp:
    bufAppendC('(');

    bufAppendS("EBinOp");

    bufAppendC(' ');

    shExpr(p->u.eBinOp_.expr_1);
  bufAppendC(' ');
    shBinop(p->u.eBinOp_.binop_);
  bufAppendC(' ');
    shExpr(p->u.eBinOp_.expr_2);

    bufAppendC(')');

    break;
  case is_EFnCall:
    bufAppendC('(');

    bufAppendS("EFnCall");

    bufAppendC(' ');

    shIdent(p->u.eFnCall_.ident_);
  bufAppendC(' ');
    shFArgs(p->u.eFnCall_.fargs_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Expr!\n");
    exit(1);
  }
}

void shBinop(Binop p)
{
  switch(p->kind)
  {
  case is_Add:

    bufAppendS("Add");




    break;
  case is_Sub:

    bufAppendS("Sub");




    break;
  case is_Mul:

    bufAppendS("Mul");




    break;
  case is_Div:

    bufAppendS("Div");




    break;
  case is_Lte:

    bufAppendS("Lte");




    break;
  case is_Eq:

    bufAppendS("Eq");




    break;
  case is_Neq:

    bufAppendS("Neq");




    break;
  case is_Gte:

    bufAppendS("Gte");




    break;
  case is_Lt:

    bufAppendS("Lt");




    break;
  case is_Gt:

    bufAppendS("Gt");




    break;
  case is_And:

    bufAppendS("And");




    break;
  case is_Or:

    bufAppendS("Or");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Binop!\n");
    exit(1);
  }
}

void shBlock(Block p)
{
  switch(p->kind)
  {
  case is_BCons:
    bufAppendC('(');

    bufAppendS("BCons");

    bufAppendC(' ');

    shState(p->u.bCons_.state_);
  bufAppendC(' ');
    shBlock(p->u.bCons_.block_);

    bufAppendC(')');

    break;
  case is_BNil:

    bufAppendS("BNil");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Block!\n");
    exit(1);
  }
}

void shState(State p)
{
  switch(p->kind)
  {
  case is_SAssn:
    bufAppendC('(');

    bufAppendS("SAssn");

    bufAppendC(' ');

    shIdent(p->u.sAssn_.ident_);
  bufAppendC(' ');
    shExpr(p->u.sAssn_.expr_);

    bufAppendC(')');

    break;
  case is_SPrint:
    bufAppendC('(');

    bufAppendS("SPrint");

    bufAppendC(' ');

    shExpr(p->u.sPrint_.expr_);

    bufAppendC(')');

    break;
  case is_SIf:
    bufAppendC('(');

    bufAppendS("SIf");

    bufAppendC(' ');

    shExpr(p->u.sIf_.expr_);
  bufAppendC(' ');
    shBlock(p->u.sIf_.block_);

    bufAppendC(')');

    break;
  case is_SIfEl:
    bufAppendC('(');

    bufAppendS("SIfEl");

    bufAppendC(' ');

    shExpr(p->u.sIfEl_.expr_);
  bufAppendC(' ');
    shBlock(p->u.sIfEl_.block_1);
  bufAppendC(' ');
    shBlock(p->u.sIfEl_.block_2);

    bufAppendC(')');

    break;
  case is_SWhile:
    bufAppendC('(');

    bufAppendS("SWhile");

    bufAppendC(' ');

    shExpr(p->u.sWhile_.expr_);
  bufAppendC(' ');
    shBlock(p->u.sWhile_.block_);

    bufAppendC(')');

    break;
  case is_SExpr:
    bufAppendC('(');

    bufAppendS("SExpr");

    bufAppendC(' ');

    shExpr(p->u.sExpr_.expr_);

    bufAppendC(')');

    break;
  case is_SRet:
    bufAppendC('(');

    bufAppendS("SRet");

    bufAppendC(' ');

    shExpr(p->u.sRet_.expr_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing State!\n");
    exit(1);
  }
}

void shFunDecl(FunDecl p)
{
  switch(p->kind)
  {
  case is_FDecl:
    bufAppendC('(');

    bufAppendS("FDecl");

    bufAppendC(' ');

    shIdent(p->u.fDecl_.ident_);
  bufAppendC(' ');
    shArgs(p->u.fDecl_.args_);
  bufAppendC(' ');
    shBlock(p->u.fDecl_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing FunDecl!\n");
    exit(1);
  }
}

void shArgs(Args p)
{
  switch(p->kind)
  {
  case is_AArgs:
    bufAppendC('(');

    bufAppendS("AArgs");

    bufAppendC(' ');

    shIdent(p->u.aArgs_.ident_);
  bufAppendC(' ');
    shArgsRest(p->u.aArgs_.argsrest_);

    bufAppendC(')');

    break;
  case is_ANone:

    bufAppendS("ANone");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Args!\n");
    exit(1);
  }
}

void shArgsRest(ArgsRest p)
{
  switch(p->kind)
  {
  case is_ACons:
    bufAppendC('(');

    bufAppendS("ACons");

    bufAppendC(' ');

    shIdent(p->u.aCons_.ident_);
  bufAppendC(' ');
    shArgsRest(p->u.aCons_.argsrest_);

    bufAppendC(')');

    break;
  case is_ANil:

    bufAppendS("ANil");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ArgsRest!\n");
    exit(1);
  }
}

void shFArgs(FArgs p)
{
  switch(p->kind)
  {
  case is_FAArgs:
    bufAppendC('(');

    bufAppendS("FAArgs");

    bufAppendC(' ');

    shExpr(p->u.fAArgs_.expr_);
  bufAppendC(' ');
    shFArgsRest(p->u.fAArgs_.fargsrest_);

    bufAppendC(')');

    break;
  case is_FANone:

    bufAppendS("FANone");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing FArgs!\n");
    exit(1);
  }
}

void shFArgsRest(FArgsRest p)
{
  switch(p->kind)
  {
  case is_FACons:
    bufAppendC('(');

    bufAppendS("FACons");

    bufAppendC(' ');

    shExpr(p->u.fACons_.expr_);
  bufAppendC(' ');
    shFArgsRest(p->u.fACons_.fargsrest_);

    bufAppendC(')');

    break;
  case is_FANil:

    bufAppendS("FANil");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing FArgsRest!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

